server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.50.86:5432/lab
    username: lab
    password: aaaa1234
  redis:
    host: 192.168.50.86
    port: 6379
    timeout: 20000