/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab.springboot.basic;

public class Library {
    public static boolean someLibraryMethod() {
        return true;
    }
}
