#ifndef __mainframe__
#define __mainframe__

/**
@file
Subclass of GUI_MainFrame, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing GUI_MainFrame */
class MainFrame : public GUI_MainFrame
{
	protected:
		// Handlers for GUI_MainFrame events.
		void OnCalculateClick( wxCommandEvent& event );
		void OnExitClick( wxCommandEvent& event );
	public:
		/** Constructor */
		MainFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __mainframe__
