application:
  security:
    oauth:
      client[0]:
        registered-redirect-uri: http://example.com
        # 客戶端 id
        client-id: client1
        # 客戶端密鑰
        client-secret: $2a$10$wlgcx61faSJ8O5I4nLiovO9T36HBQgh4RhOQAYNORCzvANlInVlw2
        # 授權範圍
        scope: all
        # token 有效期
        access-token-validity-seconds: 6000
        # 刷新 token 的有效期
        refresh-token-validity-seconds: 6000
        # 允許的授權類型
        grant-type: authorization_code,password,refresh_token
        # 可以訪問的資源 id
        resource-ids: oauth2
      client[1]:
        registered-redirect-uri: http://example.com
        # 客戶端 id
        client-id: client2
        # 客戶端密鑰
        client-secret: $2a$10$wlgcx61faSJ8O5I4nLiovO9T36HBQgh4RhOQAYNORCzvANlInVlw2
        # 授權範圍
        scope: all
        # token 有效期
        access-token-validity-seconds: 6000
        # 刷新 token 的有效期
        refresh-token-validity-seconds: 6000
        # 允許的授權類型
        grant-type: authorization_code,password,refresh_token
        # 可以訪問的資源 id
        resource-ids: oauth2